<a href="https://colab.research.google.com/github/Matiyas1994/DS_track_task/blob/main/Copy_of_Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [4]:
#your code here
import itertools

elements = ['A', 'B', 'C']
combinations = list(itertools.combinations(elements, 2))

for combination in combinations:
    print(combination)


('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [7]:
#your code here
import itertools

sequence = itertools.cycle(['Python', 'is', 'fun'])
for _ in range(10):
    print(next(sequence))

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [10]:
#your code here
import glob

all_files = glob.glob("*.py")

for file in all_files:
    print(file)

[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [11]:
#your code here
from bs4 import BeautifulSoup

def extract_text(html):
    soup = BeautifulSoup(html, 'html.parser')
    paragraph_tag = soup.find('p')
    if paragraph_tag:
        return paragraph_tag.get_text()
    else:
        return ""

html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
print(extract_text(html))


AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

> Indented block



In [12]:
#your code here
import re

def replace_ai(text):
    return re.sub(r'\bAI\b', 'Artificial Intelligence', text)

text = "AI is transforming the world"
print(replace_ai(text))

Artificial Intelligence is transforming the world


**CP6**: Create a numpy array of 10 zeros.

In [14]:
#your code here
import numpy as np

zeros = np.zeros(10)
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [15]:
#your code here
import numpy as np

arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [16]:
#your code here
import numpy as np

arr = np.arange(9).reshape((3, 3))
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

-why machine learning models require large amounts of data?

Machine learning models require a large amount of data to adequately capture the connections that may exist between input features and output features, as well as among the input features themselves. With more data, models can generalize better, make accurate predictions, and handle diverse scenarios. Large datasets also help mitigate overfitting, where the model memorizes the training data instead of learning the underlying patterns.

- What does it mean for an amount of data to be large?


**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

1. AI-Driven Autonomous Weapon Systems
Adversaries could exploit AI to develop autonomous weapon systems that can independently identify and engage targets, potentially leading to unintended casualties or escalating conflicts. These AI-driven weapons could make decisions without human intervention, raising ethical concerns and the potential for misuse.

Prevention Measures

-International Regulations: Establishing international treaties and agreements to govern the development, deployment, and use of autonomous weapon systems, ensuring adherence to ethical standards and human control requirements.

-Ethical AI Frameworks: Promoting the development and adoption of ethical AI frameworks that prioritize human values, accountability, and transparency in the design and operation of autonomous weapon systems.

2.